FROM node:18

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of backend code
COPY . .

# Expose backend port (change if needed)
EXPOSE 5000

# Start server
CMD ["npm", "start"]
